import { MovieReviews } from "../shared/types";

export const movieReviews: MovieReviews[] = [
    {
        "id": 1234,
        "reviewerName": "John Doe",
        "year": 2022,
        "genre_ids": [878],
        "original_language": "en",
        "original_title": "Rebel Moon - Part One: A Child of Fire",
        "adult": false,
        "overview": "When a peaceful colony on the edge of the galaxy finds itself threatened by the armies of the tyrannical Regent Balisarius, they dispatch Kora, a young woman with a mysterious past, to seek out warriors from neighboring planets to help them take a stand.",
        "popularity": 2136.3,
        "poster_path": "/sRLC052ieEzkQs9dEtPMfFxYkej.jpg",
        "release_date": "2023-12-15",
        "title": "Rebel Moon - Part One: A Child of Fire",
        "video": false
    },
    {
        "id": 2345,
        "reviewerName": "Alice Smith",
        "year": 2022,
        "genre_ids": [28, 12, 14],
        "original_language": "en",
        "original_title": "Aquaman and the Lost Kingdom",
        "adult": false,
        "overview": "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
        "popularity": 1605.303,
        "poster_path": "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
        "release_date": "2023-12-20",
        "title": "Aquaman and the Lost Kingdom",
        "video": false
    },
    {
        "id": 695721,
        "reviewerName": "Emma Brown",
        "year": 2022,
        "genre_ids": [18, 878, 28],
        "original_language": "en",
        "original_title": "The Hunger Games: The Ballad of Songbirds & Snakes",
        "adult": false,
        "overview": "64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.",
        "popularity": 1509.974,
        "poster_path": "/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg",
        "release_date": "2023-11-15",
        "title": "The Hunger Games: The Ballad of Songbirds & Snakes",
        "video": false
    },
    {
        "id": 9834,
        "reviewerName": "Serene Doe",
        "year": 2022,
        "genre_ids": [878],
        "original_language": "en",
        "original_title": "Rebel Moon - Part One: A Child of Fire",
        "adult": false,
        "overview": "When a peaceful colony on the edge of the galaxy finds itself threatened by the armies of the tyrannical Regent Balisarius, they dispatch Kora, a young woman with a mysterious past, to seek out warriors from neighboring planets to help them take a stand.",
        "popularity": 2136.3,
        "poster_path": "/sRLC052ieEzkQs9dEtPMfFxYkej.jpg",
        "release_date": "2023-12-15",
        "title": "Rebel Moon - Part One: A Child of Fire",
        "video": false
    },
    {
        "id": 8345,
        "reviewerName": "Chris Smith",
        "year": 2022,
        "genre_ids": [28, 12, 14],
        "original_language": "en",
        "original_title": "Aquaman and the Lost Kingdom",
        "adult": false,
        "overview": "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
        "popularity": 1605.303,
        "poster_path": "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
        "release_date": "2023-12-20",
        "title": "Aquaman and the Lost Kingdom",
        "video": false
    },
    {
        "id": 69521,
        "reviewerName": "Emma Brown",
        "year": 2022,
        "genre_ids": [18, 878, 28],
        "original_language": "en",
        "original_title": "The Hunger Games: The Ballad of Songbirds & Snakes",
        "adult": false,
        "overview": "64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.",
        "popularity": 1509.974,
        "poster_path": "/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg",
        "release_date": "2023-11-15",
        "title": "The Hunger Games: The Ballad of Songbirds & Snakes",
        "video": false
    },
    {
        "id": 1029575,
        "reviewerName": "Michael Johnson",
        "year": 2022,
        "genre_ids": [28, 35],
        "original_language": "en",
        "original_title": "The Family Plan",
        "adult": false,
        "overview": "Dan Morgan is many things: a devoted husband, a loving father, a celebrated car salesman. He's also a former assassin. And when his past catches up to his present, he's forced to take his unsuspecting family on a road trip unlike any other.",
        "popularity": 954.371,
        "poster_path": "/15Fe18IglCCP1jJoj5F529on0IA.jpg",
        "release_date": "2023-12-14",
        "title": "The Family Plan",
        "video": false
    },
    {
        "id": 787699,
        "reviewerName": "Sophia Williams",
        "year": 2022,
        "genre_ids": [35, 10751, 14],
        "original_language": "en",
        "original_title": "Wonka",
        "adult": false,
        "overview": "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
        "popularity": 949.214,
        "poster_path": "/bmlkLCjrIWnnZzdAQ4uNPG9JFdj.jpg",
        "release_date": "2023-12-06",
        "title": "Wonka",
        "video": false
    },
    {
        "id": 891699,
        "reviewerName": "David Miller",
        "year": 2022,
        "genre_ids": [28, 80],
        "original_language": "en",
        "original_title": "Silent Night",
        "adult": false,
        "overview": "A tormented father witnesses his young son die when caught in a gang's crossfire on Christmas Eve. While recovering from a wound that costs him his voice, he makes vengeance his life's mission and embarks on a punishing training regimen in order to avenge his son's death.",
        "popularity": 945.22,
        "poster_path": "/gg4zZoTggZmpAQ32qIrP5dtnkEZ.jpg",
        "release_date": "2023-11-30",
        "title": "Silent Night",
        "video": false
    }
]
